### ISSUE TITLE
CLI tutorial fails for sub create

### ISSUE THREAD

**Issue by Grant-Rc** [Azure/deployment-stacks#65]
This is autogenerated. Please review and update as needed.
Describe the bug
Command Name
az stack sub create

Errors:

The command failed with an unexpected error. Here is the traceback:
'NoneType' object has no attribute '__name__'
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 692, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/resource/custom.py", line 2087, in create_deployment_stack_at_subscription
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/resource/_client_factory.py", line 69, in _resource_deploymentstacks_client_factory
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/client_factory.py", line 70, in get_mgmt_service_client
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/client_factory.py", line 206, in _get_mgmt_service_client
AttributeError: 'NoneType' object has no attribute '__name__'

To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

Put any pre-requisite steps here...
az stack sub create -n {} -l {} -f {} -p {}
Expected Behavior
Environment Summary
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.33.0 *
Additional Context

Install CLI MSI successfully and following tutorial I get the following
![image](https://user-images.githubusercontent.com/3213940/182960634-c6698129-a3ee-450f-a896-5c6f508e9b01.png)

**Comment by harshpatel17** [comment]
This error is expected to fixed in the next Deployment Stacks release.

**Comment by dani3lh3pe** [comment]
Hi @harshpatel17, when can we expect the new version? :)
Thank you!

**Comment by harshpatel17** [comment]
@dani3lheidemann I am currently expecting the newest version to be released within 1-2 weeks. Will keep you updated.

**Comment by harshpatel17** [comment]
@DamianFlynn Before passing of the new build I wanted to confirm if you were able to do a couple of things

Open powershell as **admin**
Run the following command
& "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe" -m pip install -e **path of unzipped sdk** --force-reinstall

That error usually come from the CLI not being mapped to the SDK, the above command should fix that issue

**Comment by DamianFlynn** [comment]
@harshpatel17 i think you tagged the wrong person. My system is MacOS. 

Happy to try if you need

**Comment by harshpatel17** [comment]
> @harshpatel17 i think you tagged the wrong person. My system is MacOS.
> 
> Happy to try if you need

I did tag the wrong person, sorry about that!

**Comment by harshpatel17** [comment]
@dani3lheidemann Before passing of the new build I wanted to confirm if you were able to do a couple of things

Open powershell as admin
Run the following command
& "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe" -m pip install -e path of unzipped sdk --force-reinstall

That error usually come from the CLI not being mapped to the SDK, the above command should fix that issue

**Comment by johndowns** [comment]
I've run into this same issue with the latest preview.

azure-cli                2.44.1.post20230111200937

**Comment by harshpatel17** [comment]
@johndowns Are you using the Mac build?

**Comment by johndowns** [comment]
@harshpatel17 Yes I am. Feel free to DM one on Teams if you want to discuss.
